// This file is generated by rust-protobuf 3.7.2. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `dss/share.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_2;

// @@protoc_insertion_point(message:dss.ShareProto)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct ShareProto {
    // message fields
    // @@protoc_insertion_point(field:dss.ShareProto.id)
    pub id: u32,
    // @@protoc_insertion_point(field:dss.ShareProto.threshold)
    pub threshold: u32,
    // @@protoc_insertion_point(field:dss.ShareProto.shares_count)
    pub shares_count: u32,
    // @@protoc_insertion_point(field:dss.ShareProto.data)
    pub data: ::std::vec::Vec<u8>,
    // @@protoc_insertion_point(field:dss.ShareProto.hash)
    pub hash: ::std::vec::Vec<u8>,
    // @@protoc_insertion_point(field:dss.ShareProto.meta_data)
    pub meta_data: ::protobuf::MessageField<super::metadata::MetaDataProto>,
    // special fields
    // @@protoc_insertion_point(special_field:dss.ShareProto.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a ShareProto {
    fn default() -> &'a ShareProto {
        <ShareProto as ::protobuf::Message>::default_instance()
    }
}

impl ShareProto {
    pub fn new() -> ShareProto {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(6);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "id",
            |m: &ShareProto| { &m.id },
            |m: &mut ShareProto| { &mut m.id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "threshold",
            |m: &ShareProto| { &m.threshold },
            |m: &mut ShareProto| { &mut m.threshold },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "shares_count",
            |m: &ShareProto| { &m.shares_count },
            |m: &mut ShareProto| { &mut m.shares_count },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "data",
            |m: &ShareProto| { &m.data },
            |m: &mut ShareProto| { &mut m.data },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "hash",
            |m: &ShareProto| { &m.hash },
            |m: &mut ShareProto| { &mut m.hash },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::metadata::MetaDataProto>(
            "meta_data",
            |m: &ShareProto| { &m.meta_data },
            |m: &mut ShareProto| { &mut m.meta_data },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<ShareProto>(
            "ShareProto",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for ShareProto {
    const NAME: &'static str = "ShareProto";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.id = is.read_uint32()?;
                },
                16 => {
                    self.threshold = is.read_uint32()?;
                },
                24 => {
                    self.shares_count = is.read_uint32()?;
                },
                34 => {
                    self.data = is.read_bytes()?;
                },
                42 => {
                    self.hash = is.read_bytes()?;
                },
                50 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.meta_data)?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.id != 0 {
            my_size += ::protobuf::rt::uint32_size(1, self.id);
        }
        if self.threshold != 0 {
            my_size += ::protobuf::rt::uint32_size(2, self.threshold);
        }
        if self.shares_count != 0 {
            my_size += ::protobuf::rt::uint32_size(3, self.shares_count);
        }
        if !self.data.is_empty() {
            my_size += ::protobuf::rt::bytes_size(4, &self.data);
        }
        if !self.hash.is_empty() {
            my_size += ::protobuf::rt::bytes_size(5, &self.hash);
        }
        if let Some(v) = self.meta_data.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.id != 0 {
            os.write_uint32(1, self.id)?;
        }
        if self.threshold != 0 {
            os.write_uint32(2, self.threshold)?;
        }
        if self.shares_count != 0 {
            os.write_uint32(3, self.shares_count)?;
        }
        if !self.data.is_empty() {
            os.write_bytes(4, &self.data)?;
        }
        if !self.hash.is_empty() {
            os.write_bytes(5, &self.hash)?;
        }
        if let Some(v) = self.meta_data.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(6, v, os)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> ShareProto {
        ShareProto::new()
    }

    fn clear(&mut self) {
        self.id = 0;
        self.threshold = 0;
        self.shares_count = 0;
        self.data.clear();
        self.hash.clear();
        self.meta_data.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static ShareProto {
        static instance: ShareProto = ShareProto {
            id: 0,
            threshold: 0,
            shares_count: 0,
            data: ::std::vec::Vec::new(),
            hash: ::std::vec::Vec::new(),
            meta_data: ::protobuf::MessageField::none(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for ShareProto {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("ShareProto").unwrap()).clone()
    }
}

impl ::std::fmt::Display for ShareProto {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ShareProto {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x0fdss/share.proto\x12\x03dss\x1a\x12dss/metadata.proto\"\xb6\x01\n\n\
    ShareProto\x12\x0e\n\x02id\x18\x01\x20\x01(\rR\x02id\x12\x1c\n\tthreshol\
    d\x18\x02\x20\x01(\rR\tthreshold\x12!\n\x0cshares_count\x18\x03\x20\x01(\
    \rR\x0bsharesCount\x12\x12\n\x04data\x18\x04\x20\x01(\x0cR\x04data\x12\
    \x12\n\x04hash\x18\x05\x20\x01(\x0cR\x04hash\x12/\n\tmeta_data\x18\x06\
    \x20\x01(\x0b2\x12.dss.MetaDataProtoR\x08metaDatab\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(1);
            deps.push(super::metadata::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(ShareProto::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
